### ISSUE TITLE
AdminBar shouldn't be loaded when in Admin

### ISSUE THREAD

**Issue by teppokoivula** [apeisa/AdminBar#11]
We've had issues with AdminBar loading in admin context. This is especially harmful when dealing with PageTable field, as the JavaScript redirect pretty much renders this module unusable (or PageTable unusable, depending on your point of view).

I've just changed AdminBar locally to add _some of_ it's hooks in ready() instead of init(), since there we've got access to $page, and added a check for current page:

```
@@ -13,7 +13,7 @@
            'title' => 'Admin Bar',
            'summary' => 'Fast and easy in-page content editing',
            'href' => 'http://processwire.com/talk/index.php/topic,56.0.html',
-           'version' => 101,
+           'version' => 102,
            'permanent' => false,
            'autoload' => true,
            'singular' => true,
@@ -52,6 +52,12 @@
    }

    /**
+    * Permission required by our module
+    *
+    */
+   protected $ab_permission;
+
+   /**
     * Initialize the module and setup hooks
     *
     * The init method of a module is called right after ProcessWire is bootstrapped, when all
@@ -74,15 +80,28 @@

        if ($this->user->isGuest()) return false;

-       $ab_permission = $this->permissions->get('adminbar');
-       if(!$this->user->hasPermission($ab_permission)) return false;
+       $this->ab_permission = $this->permissions->get('adminbar');
+       if(!$this->user->hasPermission($this->ab_permission)) return false;

+       // hook before forms are rendered, so that we can modify the form's "action" attribute
+       $this->addHookBefore('InputfieldForm::render', $this, 'formRender');
+   }
+
+   /**
+    * Setup rest of the hooks
+    *
+    * Some hooks have to be defined here, since we need access to $page var.
+    *
+    */
+   public function ready() {
+
+       if ($this->user->isGuest() || ($this->page && $this->page->template == "admin")) return false;
+
+       if(!$this->user->hasPermission($this->ab_permission)) return false;
+
        $this->pages->addHookAfter('save', $this, 'pageSave');
        $this->addHookAfter('Page::render', $this, "pageRender");

-       // hook before forms are rendered, so that we can modify the form's "action" attribute
-       $this->addHookBefore('InputfieldForm::render', $this, 'formRender');
-
        // hook before a redirect occurs, os we can modify the redirect URL
        $this->session->addHookBefore('redirect', $this, 'sessionRedirect');
    }
```

What do you think, would this be valid solution, and could the module be updated to this? Any better ideas? I was going to add a check to JS first, but this seems to work much better -- unless there's some reason to load AdminBar in admin context, that is..

Module.php claims that init() is "required", but so far this seems to work perfectly without it too.. might be something that has changed since then, but to guarantee backwards compatibility, empty init() method should probably be added.. and comments should definitely be updated too :)

For the record, this seems to be the cause of https://github.com/ryancramerdesign/ProcessWire/issues/775#issuecomment-61838238, and I've seen a few similar reports.

**Note: updated the code above, InputfieldForm::render hook has to be attached in init() and is needed to support older ProcessWire versions.**

**Comment by adrianbj** [comment]
Thanks teppo - this seems to have fixed those issues for me also. 

Antti - any chance of getting these incorporated?

**Comment by adrianbj** [comment]
Just wanted to note back here that unfortunately those fixes didn't work fully - honestly can't remember what scenarios anymore, but with some in ready() instead of init() not everything worked. I ended up going with appening another variable to the URL: ab=1 and passing that around and checking for that rather than modal=1. That seems to take care of making everything work on the front end without affecting the admin modals. My code needs some cleaning up, but at some point I will try to remember to post everything here.

I also managed to add an Edit Profile link to the admin bar and get that working, which is quite nice compared with messing around with a dedicated front-end form, especially with user avatar image editing etc.

**Comment by teppokoivula** [comment]
Thanks for the heads-up, @adrianbj. Would be very interesting to know what kind of issues this caused. I'm running a modified version of AdminBar on a bunch of sites, and haven't seen any issues yet, but wouldn't want one to catch me by surprise either :)

Extra GET param sounds like a valid solution, though personally I'd prefer a solution that avoids unnecessarily attaching/executing the hook methods.

**Comment by adrianbj** [comment]
@teppokoivula - could you maybe send me your final modified version so I can take a look. Using your diff above didn't work. Even attempting to tweak things didn't result in a working solution - I think it was an issue with what was being returned by $page->template but I might be remembering incorrectly.

**Comment by teppokoivula** [comment]
@adrianbj Right, sorry! Just had another look at this, and it seems that I've fixed some issues locally, and forgot to update them here. In essence, some things still need to be done during init().

Will post new version later, once I'm able to iron out one additional weirdness :)

**Comment by teppokoivula** [comment]
@adrianbj @apeisa I just pushed an updated version of AdminBar with the fixes discussed here to https://github.com/teppokoivula/AdminBar. Adrian, if you take a closer look at this, please let me know if there's anything wrong with it.

For the record, so far I've tested this with multiple sites ranging from 2.2.9 to 2.5.4. So far no tests with the dev branch, but will take a look at that later.. though it'd be kind of weird if something was broken there :)

Note that my version actually contains a fix for issue #8. This is something that @niklaka fixed over a year ago, but the issue is still open here in GitHub. Perhaps @apeisa could take a look at this too?

I can send a pull request for both of these changes, if that's easier to handle --assuming that they work, of course.

**Comment by adrianbj** [comment]
Thanks @teppokoivula for the new version

These are the issues I have seen so far:
```
Fatal error: Call to a member function isDefault() on null in /site/modules/AdminBar/AdminBar.module on line 214
```
and also when I edit a page, admin bar disappears until I save it.

I am running very recent dev versions on the couple of installs I just tested this on.

Sorry, I don't any time to investigate fully right now.

**Comment by teppokoivula** [comment]
Thanks, @adrianbj. That fatal error sounds like the result of language support not being installed, will have to add another check for that apparently. In our environment it's always enabled, so didn't think of this :)

Latter issue isn't as obvious, I'm afraid, and I'm not even entirely sure I really understand what you mean; when you hit "edit", whole AdminBar disappears? I'm testing this on latest dev right now, and so far I've been unable to track this down.

Sounds like it could be a browser issue too -- which platform and browser are you on?

**Comment by teppokoivula** [comment]
@adrianbj: just pushed a fix for the LanguageSupport issue (fatal error), but the latter issue remains a mystery. Cant reproduce that on my test sites; PW 2.5.26 and s far tested Chrome, Firefox, and Safari on OS X. Don't have any Windows machines here, but I can run some additional tests tomorrow.

**Comment by teppokoivula** [comment]
Another idea for the "AdminBar going away" issue: please make sure that you've loaded jQuery. Just noticed that at least some of the default site profiles don't load it by default, and this could result in AdminBar buttons just redirecting the user to new page. Kind of matches the reported issue.

(AdminBar has a module setting for loading jQuery for cases like this.)

**Comment by adrianbj** [comment]
Thanks for the language check - seems to be fine now.

Sorry for the jquery issue - I was testing on on an install without jquery. It's fine now.

So far it looks to be working well - I'll test a little more thoroughly shortly and see how well it works in a the situation I need it for. 

I just checked your code revisions and see that you did almost exactly what I described above with adding a new get variable to the URLs - I thought we were trying to avoid that :)

**Comment by teppokoivula** [comment]
Well, tried and failed, kind of. In my case I need this to work for PW versions both old and new, and in the end the GET param route was the only one that didn't require much more extensive rewrite. Would've preferred an even cleaner solution, but that's just too much hassle right now :)

**Comment by adrianbj** [comment]
That was exactly my attitude after trying for a while to make it work without :)

I have actually ended up styling it to match my site, changed icons, disabled the admin link for most users, added a link to edit the user profile, added some additional conditions to only allow a user to edit pages they have created, except for site editors, and a few other things.

I think it has resulted in a very clean and powerful way for to provide front-end content creation and editing without the need to create front-end forms, which I have done many times in the past, but for complicated stuff it always seems to be a shame to have to recreate what PW does so well. I think AdminBar is a great solution, but I think it pays to do some site by site and need by need customization on it.
